# Generated by Django 3.1.7 on 2021-05-19 21:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0003_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assignees',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
