# Generated by Django 3.1.7 on 2021-05-20 16:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20210519_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='dateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
