# Generated by Django 3.1.7 on 2021-05-20 16:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0005_task_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assignees',
            field=models.ManyToManyField(default=None, related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
